# Generated by Django 2.2.7 on 2020-01-29 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='board',
            options={'ordering': ['-createTime']},
        ),
        migrations.RemoveField(
            model_name='board',
            name='text',
        ),
        migrations.RemoveField(
            model_name='board',
            name='updateTime',
        ),
        migrations.AddField(
            model_name='board',
            name='contents',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='board',
            name='writer',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='board',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
