# Generated by Django 2.2.7 on 2020-01-24 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='aboutMe',
            field=models.TextField(blank=True, help_text='Introduce yourself', max_length=1000),
        ),
    ]
