# Generated by Django 2.2.7 on 2020-01-24 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20200124_1415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='nick',
            field=models.CharField(blank=True, max_length=50, verbose_name='NickName'),
        ),
    ]
