# Generated by Django 2.2.7 on 2020-01-24 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20200124_1436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='birth_date',
            field=models.DateTimeField(blank=True, help_text='YYYY-MM-DD', null=True),
        ),
    ]
